### ISSUE TITLE
About IHR description

### ISSUE THREAD

**Issue by cruisezhou** [seemoo-lab/d11-emu#1]
Hi:
  Thanks for your fabulous work. I am learning from it to research how commercial Wifi MAC is implemented. But there is a point makes me confused. The IHRs described in src/include/ihr.rs are much more than what we can find from the "d11.h" both from linux driver and asuswrt-phantom. So I wonders where I can find the header file which describe as many IHR as you did. 
Thanks!
Best wishses!

**Comment by jlinktu** [comment]
Hi @cruisezhou,
the IHR defines that you can find in `src/include/ihr.rs` were gathered from various sources, including different versions of header files, drivers, published research results, and firmware blob analysis. But we do not have a list of sources or documentation of the gathering process. It is rather something that happened whilst working with nexmon and ucodes of various devices over a longer time-period.

**Comment by cruisezhou** [comment]
> Hi @cruisezhou, the IHR defines that you can find in `src/include/ihr.rs` were gathered from various sources, including different versions of header files, drivers, published research results, and firmware blob analysis. But we do not have a list of sources or documentation of the gathering process. It is rather something that happened whilst working with nexmon and ucodes of various devices over a longer time-period.

@jlinktu  Thanks for your reply. I would continue to work with nexmon and your other projects.
